[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Fuzzer for fixed point arithmetic primitives."
documentation = "https://docs.rs/sp-arithmetic-fuzzer"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-arithmetic-fuzzer"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
honggfuzz = "0.5.49"
num-bigint = "0.2"
primitive-types = "0.10.1"
sp-arithmetic = {version = "4.0.0", path = ".."}

[[bin]]
name = "biguint"
path = "src/biguint.rs"

[[bin]]
name = "normalize"
path = "src/normalize.rs"

[[bin]]
name = "per_thing_rational"
path = "src/per_thing_rational.rs"

[[bin]]
name = "multiply_by_rational"
path = "src/multiply_by_rational.rs"

[[bin]]
name = "fixed_point"
path = "src/fixed_point.rs"
