[package]
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-runtime-test"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/core"}
sp-io = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/io"}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime"}
sp-sandbox = {version = "0.10.0-dev", default-features = false, path = "../../../primitives/sandbox"}
sp-std = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/std"}
sp-tasks = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/tasks"}

[build-dependencies]
substrate-wasm-builder = {version = "5.0.0-dev", path = "../../../utils/wasm-builder"}

[features]
default = ["std"]
std = [
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-sandbox/std",
  "sp-std/std",
  "sp-tasks/std",
]
