[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "node-primitives"
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
  "derive",
]}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../../../frame/system"}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
sp-application-crypto = {version = "4.0.0", default-features = false, path = "../../../primitives/application-crypto"}
sp-core = {version = "4.1.0-dev", default-features = false, path = "../../../primitives/core"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../../primitives/runtime"}

[features]
default = ["std"]
std = [
  "codec/std",
  "scale-info/std",
  "frame-system/std",
  "sp-application-crypto/std",
  "sp-core/std",
  "sp-runtime/std",
]
