[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "RPC for the BEEFY Client gadget for substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "beefy-gadget-rpc"
repository = "https://github.com/ultrastable-money/substrate"
version = "4.0.0-dev"

[dependencies]
futures = "0.3.16"
log = "0.4"
serde = {version = "1.0.130", features = ["derive"]}

jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-pubsub = "18.0.0"

codec = {version = "2.2.0", package = "parity-scale-codec", features = ["derive"]}

sc-rpc = {version = "4.0.0-dev", path = "../../rpc"}

sp-core = {version = "4.0.0", path = "../../../primitives/core"}
sp-runtime = {version = "4.0.0-dev", path = "../../../primitives/runtime"}

beefy-gadget = {version = "4.0.0-dev", path = "../."}
beefy-primitives = {version = "4.0.0-dev", path = "../../../primitives/beefy"}
