[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "RPC for the BEEFY Client gadget for substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "beefy-gadget-rpc"
repository = "https://github.com/ultrastable-money/substrate"
version = "4.0.0-dev"

[dependencies]
derive_more = "0.99"
futures = "0.3.16"
log = "0.4"
parking_lot = "0.11"
serde = {version = "1.0.132", features = ["derive"]}
thiserror = "1.0"

jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-pubsub = "18.0.0"

codec = {version = "2.2.0", package = "parity-scale-codec", features = ["derive"]}

sc-rpc = {version = "4.0.0-dev", path = "../../rpc"}
sc-utils = {version = "4.0.0-dev", path = "../../utils"}

sp-core = {version = "4.1.0-dev", path = "../../../primitives/core"}
sp-runtime = {version = "4.1.0-dev", path = "../../../primitives/runtime"}

beefy-gadget = {version = "4.0.0-dev", path = "../."}
beefy-primitives = {version = "4.0.0-dev", path = "../../../primitives/beefy"}

[dev-dependencies]
serde_json = "1.0.74"

sc-rpc = {version = "4.0.0-dev", path = "../../rpc", features = [
  "test-helpers",
]}
substrate-test-runtime-client = {version = "2.0.0", path = "../../../test-utils/runtime/client"}
