[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "This crate provides an implementation of `WasmRuntime` that is baked by wasmi."
documentation = "https://docs.rs/sc-executor-wasmi"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-executor-wasmi"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
log = "0.4.8"
sc-allocator = {version = "4.0.0-dev", path = "../../allocator"}
sc-executor-common = {version = "0.10.0-dev", path = "../common"}
scoped-tls = "1.0"
sp-core = {version = "4.0.0-dev", path = "../../../primitives/core"}
sp-runtime-interface = {version = "4.0.0-dev", path = "../../../primitives/runtime-interface"}
sp-wasm-interface = {version = "4.0.0-dev", path = "../../../primitives/wasm-interface"}
wasmi = "0.9.0"
