[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Macros for declaring and implementing runtime apis."
documentation = "https://docs.rs/sp-api-proc-macro"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-api-proc-macro"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
blake2-rfc = {version = "0.2.18", default-features = false}
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.29"
quote = "1.0.10"
syn = {version = "1.0.81", features = ["full", "fold", "extra-traits", "visit"]}

# Required for the doc tests
[features]
default = ["std"]
std = []
