[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME pallet for storing preimages of hashes"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-preimage"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}

frame-benchmarking = {version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true}
frame-support = {version = "4.0.0-dev", default-features = false, path = "../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../system"}
sp-core = {version = "4.1.0-dev", default-features = false, optional = true, path = "../../primitives/core"}
sp-io = {version = "4.0.0-dev", default-features = false, path = "../../primitives/io"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../primitives/runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../../primitives/std"}

[dev-dependencies]
pallet-balances = {version = "4.0.0-dev", path = "../balances"}
sp-core = {version = "4.1.0-dev", path = "../../primitives/core", default-features = false}

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
  "codec/std",
  "scale-info/std",
  "sp-std/std",
  "sp-io/std",
  "sp-core/std",
  "sp-runtime/std",
  "frame-system/std",
  "frame-support/std",
  "frame-benchmarking/std",
]
try-runtime = ["frame-support/try-runtime"]
