[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "node-inspect"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.9.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
derive_more = "0.99"
sc-cli = {version = "0.10.0-dev", path = "../../../client/cli"}
sc-client-api = {version = "4.0.0-dev", path = "../../../client/api"}
sc-executor = {version = "0.10.0-dev", path = "../../../client/executor"}
sc-service = {version = "0.10.0-dev", default-features = false, path = "../../../client/service"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
sp-core = {version = "4.0.0-dev", path = "../../../primitives/core"}
sp-runtime = {version = "4.0.0-dev", path = "../../../primitives/runtime"}
structopt = "0.3.8"
