[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Macros to derive runtime debug implementation."
documentation = "https://docs.rs/sp-debug-derive"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-debug-derive"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.10"
syn = "1.0.81"

[features]
default = ["std"]
std = []
# By default `RuntimeDebug` implements `Debug` that outputs `<wasm:stripped>` when `std` is
# disabled. However, sometimes downstream users need to have the real `Debug` implementation for
# debugging purposes. If this is required, a user only needs to add this crate as a dependency of
# their runtime and enable the `force-debug` feature.
force-debug = []

[dev-dependencies]
