[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "subkey"
publish = false
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "subkey"
path = "src/main.rs"

[dependencies]
sc-cli = {version = "0.10.0-dev", path = "../../../client/cli"}
structopt = "0.3.14"
