[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate State Machine"
documentation = "https://docs.rs/sp-state-machine"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-state-machine"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
hash-db = {version = "0.15.2", default-features = false}
log = {version = "0.4.11", optional = true}
num-traits = {version = "0.2.8", default-features = false}
parking_lot = {version = "0.11.1", optional = true}
rand = {version = "0.7.2", optional = true}
smallvec = "1.7.0"
sp-core = {version = "4.0.0", path = "../core", default-features = false}
sp-externalities = {version = "0.10.0", path = "../externalities", default-features = false}
sp-panic-handler = {version = "4.0.0-dev", path = "../panic-handler", optional = true}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}
sp-trie = {version = "4.0.0-dev", path = "../trie", default-features = false}
thiserror = {version = "1.0.30", optional = true}
tracing = {version = "0.1.29", optional = true}
trie-db = {version = "0.22.6", default-features = false}
trie-root = {version = "0.16.0", default-features = false}

[dev-dependencies]
hex-literal = "0.3.4"
pretty_assertions = "1.0.0"
rand = "0.7.2"
sp-runtime = {version = "4.0.0-dev", path = "../runtime"}

[features]
default = ["std"]
std = [
  "codec/std",
  "hash-db/std",
  "num-traits/std",
  "sp-core/std",
  "sp-externalities/std",
  "sp-std/std",
  "sp-trie/std",
  "trie-db/std",
  "trie-root/std",
  "log",
  "thiserror",
  "parking_lot",
  "rand",
  "sp-panic-handler",
  "tracing",
]
