[package]
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-test-runtime"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
frame-support = {version = "4.0.0-dev", default-features = false, path = "../../frame/support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../../frame/system"}
frame-system-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, path = "../../frame/system/rpc/runtime-api"}
memory-db = {version = "0.27.0", default-features = false}
pallet-babe = {version = "4.0.0-dev", default-features = false, path = "../../frame/babe"}
pallet-timestamp = {version = "4.0.0-dev", default-features = false, path = "../../frame/timestamp"}
parity-util-mem = {version = "0.10.2", default-features = false, features = ["primitive-types"]}
sc-service = {version = "0.10.0-dev", default-features = false, optional = true, features = ["test-helpers"], path = "../../client/service"}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
sp-api = {version = "4.0.0-dev", default-features = false, path = "../../primitives/api"}
sp-application-crypto = {version = "4.0.0", default-features = false, path = "../../primitives/application-crypto"}
sp-block-builder = {version = "4.0.0-dev", default-features = false, path = "../../primitives/block-builder"}
sp-consensus-aura = {version = "0.10.0-dev", default-features = false, path = "../../primitives/consensus/aura"}
sp-consensus-babe = {version = "0.10.0-dev", default-features = false, path = "../../primitives/consensus/babe"}
sp-core = {version = "4.1.0-dev", default-features = false, path = "../../primitives/core"}
sp-externalities = {version = "0.10.0", default-features = false, path = "../../primitives/externalities"}
sp-finality-grandpa = {version = "4.0.0-dev", default-features = false, path = "../../primitives/finality-grandpa"}
sp-inherents = {version = "4.0.0-dev", default-features = false, path = "../../primitives/inherents"}
sp-io = {version = "4.0.0", default-features = false, path = "../../primitives/io"}
sp-keyring = {version = "4.1.0-dev", optional = true, path = "../../primitives/keyring"}
sp-offchain = {version = "4.0.0-dev", default-features = false, path = "../../primitives/offchain"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../primitives/runtime"}
sp-runtime-interface = {version = "4.1.0-dev", default-features = false, path = "../../primitives/runtime-interface"}
sp-session = {version = "4.0.0-dev", default-features = false, path = "../../primitives/session"}
sp-state-machine = {version = "0.10.0", default-features = false, path = "../../primitives/state-machine"}
sp-std = {version = "4.0.0", default-features = false, path = "../../primitives/std"}
sp-transaction-pool = {version = "4.0.0-dev", default-features = false, path = "../../primitives/transaction-pool"}
sp-trie = {version = "4.0.0", default-features = false, path = "../../primitives/trie"}
sp-version = {version = "4.0.0-dev", default-features = false, path = "../../primitives/version"}
trie-db = {version = "0.23.0", default-features = false}

# 3rd party
cfg-if = "1.0"
log = {version = "0.4.14", default-features = false}
serde = {version = "1.0.132", optional = true, features = ["derive"]}

[dev-dependencies]
futures = "0.3.9"
sc-block-builder = {version = "0.10.0-dev", path = "../../client/block-builder"}
sc-executor = {version = "0.10.0-dev", path = "../../client/executor"}
sp-consensus = {version = "0.10.0-dev", path = "../../primitives/consensus/common"}
substrate-test-runtime-client = {version = "2.0.0", path = "./client"}

[build-dependencies]
substrate-wasm-builder = {version = "5.0.0-dev", path = "../../utils/wasm-builder"}

[features]
default = [
  "std",
]
std = [
  "sp-application-crypto/std",
  "sp-consensus-aura/std",
  "sp-consensus-babe/std",
  "sp-block-builder/std",
  "codec/std",
  "scale-info/std",
  "sp-inherents/std",
  "sp-keyring",
  "log/std",
  "memory-db/std",
  "sp-offchain/std",
  "sp-core/std",
  "sp-core/std",
  "sp-std/std",
  "sp-runtime-interface/std",
  "sp-io/std",
  "frame-support/std",
  "sp-version/std",
  "serde",
  "sp-session/std",
  "sp-api/std",
  "sp-runtime/std",
  "sp-externalities/std",
  "sp-state-machine/std",
  "pallet-babe/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "pallet-timestamp/std",
  "sc-service",
  "sp-finality-grandpa/std",
  "sp-trie/std",
  "sp-transaction-pool/std",
  "trie-db/std",
]
# Special feature to disable logging
disable-logging = ["sp-api/disable-logging"]
