[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "An externalities provided environemnt that can load itself from remote nodes or cache files"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "remote-externalities"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = {version = "0.4.1", features = ["ws-client", "macros"]}

codec = {package = "parity-scale-codec", version = "2.0.0"}
env_logger = "0.9"
frame-support = {path = "../../../frame/support", optional = true, version = "4.0.0-dev"}
log = "0.4.11"
serde = "1.0.126"
serde_json = "1.0"

sp-core = {version = "4.0.0", path = "../../../primitives/core"}
sp-io = {version = "4.0.0-dev", path = "../../../primitives/io"}
sp-runtime = {version = "4.0.0-dev", path = "../../../primitives/runtime"}
sp-version = {version = "4.0.0-dev", path = "../../../primitives/version"}

[dev-dependencies]
frame-support = {path = "../../../frame/support", version = "4.0.0-dev"}
pallet-elections-phragmen = {path = "../../../frame/elections-phragmen", version = "5.0.0-dev"}
tokio = {version = "1.13", features = ["macros", "rt-multi-thread"]}

[features]
remote-test = ["frame-support"]
