[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Runtime API definition required by System RPC extensions."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "frame-system-rpc-runtime-api"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
sp-api = {version = "4.0.0-dev", default-features = false, path = "../../../../primitives/api"}

[features]
default = ["std"]
std = [
  "sp-api/std",
  "codec/std",
]
