[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Custom panic hook with bug report link"
documentation = "https://docs.rs/sp-panic-handler"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-panic-handler"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
backtrace = "0.3.63"
lazy_static = "1.4.0"
regex = "1.5.4"
