[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "A crate that provides means of executing/dispatching calls into the runtime."
documentation = "https://docs.rs/sc-executor"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-executor"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
lazy_static = "1.4.0"
libsecp256k1 = "0.6"
log = "0.4.8"
parking_lot = "0.11.1"
sc-executor-common = {version = "0.10.0-dev", path = "common"}
sc-executor-wasmi = {version = "0.10.0-dev", path = "wasmi"}
sc-executor-wasmtime = {version = "0.10.0-dev", path = "wasmtime", optional = true}
sp-api = {version = "4.0.0-dev", path = "../../primitives/api"}
sp-core = {version = "4.0.0-dev", path = "../../primitives/core"}
sp-externalities = {version = "0.10.0-dev", path = "../../primitives/externalities"}
sp-io = {version = "4.0.0-dev", path = "../../primitives/io"}
sp-panic-handler = {version = "3.0.0", path = "../../primitives/panic-handler"}
sp-runtime-interface = {version = "4.0.0-dev", path = "../../primitives/runtime-interface"}
sp-tasks = {version = "4.0.0-dev", path = "../../primitives/tasks"}
sp-trie = {version = "4.0.0-dev", path = "../../primitives/trie"}
sp-version = {version = "4.0.0-dev", path = "../../primitives/version"}
sp-wasm-interface = {version = "4.0.0-dev", path = "../../primitives/wasm-interface"}
wasmi = "0.9.0"

[dev-dependencies]
hex-literal = "0.3.3"
paste = "1.0"
regex = "1"
sc-runtime-test = {version = "2.0.0", path = "runtime-test"}
sc-tracing = {version = "4.0.0-dev", path = "../tracing"}
sp-maybe-compressed-blob = {version = "4.0.0-dev", path = "../../primitives/maybe-compressed-blob"}
sp-runtime = {version = "4.0.0-dev", path = "../../primitives/runtime"}
sp-state-machine = {version = "0.10.0-dev", path = "../../primitives/state-machine"}
substrate-test-runtime = {version = "2.0.0", path = "../../test-utils/runtime"}
tracing = "0.1.29"
tracing-subscriber = "0.2.19"
wat = "1.0"

[features]
default = ["std"]
# This crate does not have `no_std` support, we just require this for tests
std = []
wasm-extern-trace = []
wasmer-sandbox = ["sc-executor-common/wasmer-sandbox"]
wasmi-errno = ["wasmi/errno"]
wasmtime = ["sc-executor-wasmtime"]
