[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME's system exposed over Substrate RPC"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-frame-rpc-system"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
frame-system-rpc-runtime-api = {version = "4.0.0-dev", path = "../../../../frame/system/rpc/runtime-api"}
futures = "0.3.16"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
log = "0.4.8"
sc-client-api = {version = "4.0.0-dev", path = "../../../../client/api"}
sc-rpc-api = {version = "0.10.0-dev", path = "../../../../client/rpc-api"}
sc-transaction-pool-api = {version = "4.0.0-dev", path = "../../../../client/transaction-pool/api"}
sp-api = {version = "4.0.0-dev", path = "../../../../primitives/api"}
sp-block-builder = {version = "4.0.0-dev", path = "../../../../primitives/block-builder"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../../primitives/blockchain"}
sp-core = {version = "4.1.0-dev", path = "../../../../primitives/core"}
sp-runtime = {version = "4.1.0-dev", path = "../../../../primitives/runtime"}

[dev-dependencies]
sc-transaction-pool = {version = "4.0.0-dev", path = "../../../../client/transaction-pool"}
sp-tracing = {version = "4.0.0", path = "../../../../primitives/tracing"}
substrate-test-runtime-client = {version = "2.0.0", path = "../../../../test-utils/runtime/client"}
