[package]
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-runtime-interface-test-wasm"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = {version = "4.0.0", default-features = false, path = "../../core"}
sp-io = {version = "4.0.0-dev", default-features = false, path = "../../io"}
sp-runtime-interface = {version = "4.0.0", default-features = false, path = "../"}
sp-std = {version = "4.0.0", default-features = false, path = "../../std"}

[build-dependencies]
substrate-wasm-builder = {version = "5.0.0-dev", path = "../../../utils/wasm-builder"}

[features]
default = ["std"]
std = ["sp-runtime-interface/std", "sp-std/std", "sp-core/std", "sp-io/std"]
