[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "A no-std/Substrate compatible library to construct binary merkle tree."
edition = "2021"
license = "Apache-2.0"
name = "beefy-merkle-tree"
repository = "https://github.com/ultrastable-money/substrate"
version = "4.0.0-dev"

[dependencies]
hex = {version = "0.4", optional = true, default-features = false}
log = {version = "0.4", optional = true, default-features = false}
tiny-keccak = {version = "2.0.2", features = ["keccak"], optional = true}

[dev-dependencies]
env_logger = "0.9"
hex = "0.4"
hex-literal = "0.3"

[features]
debug = ["hex", "hex/std", "log"]
default = ["std", "debug", "keccak"]
keccak = ["tiny-keccak"]
std = []
