[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Basic implementation of block-authoring logic."
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-basic-authorship"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
futures = "0.3.9"
futures-timer = "3.0.1"
log = "0.4.8"
prometheus-endpoint = {package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.10.0-dev"}
sc-block-builder = {version = "0.10.0-dev", path = "../block-builder"}
sc-client-api = {version = "4.0.0-dev", path = "../api"}
sc-proposer-metrics = {version = "0.10.0-dev", path = "../proposer-metrics"}
sc-telemetry = {version = "4.0.0-dev", path = "../telemetry"}
sc-transaction-pool-api = {version = "4.0.0-dev", path = "../../client/transaction-pool/api"}
sp-api = {version = "4.0.0-dev", path = "../../primitives/api"}
sp-blockchain = {version = "4.0.0-dev", path = "../../primitives/blockchain"}
sp-consensus = {version = "0.10.0-dev", path = "../../primitives/consensus/common"}
sp-core = {version = "4.0.0", path = "../../primitives/core"}
sp-inherents = {version = "4.0.0-dev", path = "../../primitives/inherents"}
sp-runtime = {version = "4.0.0-dev", path = "../../primitives/runtime"}

[dev-dependencies]
parking_lot = "0.11.1"
sc-transaction-pool = {version = "4.0.0-dev", path = "../transaction-pool"}
substrate-test-runtime-client = {version = "2.0.0", path = "../../test-utils/runtime/client"}
