[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "node-rpc-client"
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.16"
jsonrpc-core-client = {version = "18.0.0", default-features = false, features = [
  "http",
]}
node-primitives = {version = "2.0.0", path = "../primitives"}
sc-rpc = {version = "4.0.0-dev", path = "../../../client/rpc"}
sp-tracing = {version = "4.0.0-dev", path = "../../../primitives/tracing"}
