[package]
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "chain-spec-builder"
publish = false
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = "0.12.1"
node-cli = {version = "3.0.0-dev", path = "../../node/cli"}
rand = "0.7.2"
sc-chain-spec = {version = "4.0.0-dev", path = "../../../client/chain-spec"}
sc-keystore = {version = "4.0.0-dev", path = "../../../client/keystore"}
sp-core = {version = "4.0.0", path = "../../../primitives/core"}
sp-keystore = {version = "0.10.0-dev", path = "../../../primitives/keystore"}
structopt = "0.3.25"
