[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "pallet to manage transaction payments in assets"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-asset-tx-payment"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
sp-core = {version = "4.1.0-dev", default-features = false, path = "../../../primitives/core"}
sp-io = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/io"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../../primitives/runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../../../primitives/std"}

frame-support = {version = "4.0.0-dev", default-features = false, path = "../../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../../system"}
pallet-transaction-payment = {version = "4.0.0-dev", default-features = false, path = ".."}

# Other dependencies
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.132", optional = true}

[dev-dependencies]
serde_json = "1.0.74"
smallvec = "1.7.0"

sp-storage = {version = "4.0.0", default-features = false, path = "../../../primitives/storage"}

pallet-assets = {version = "4.0.0-dev", path = "../../assets"}
pallet-authorship = {version = "4.0.0-dev", path = "../../authorship"}
pallet-balances = {version = "4.0.0-dev", path = "../../balances"}

[features]
default = ["std"]
std = [
  "serde",
  "codec/std",
  "sp-std/std",
  "sp-runtime/std",
  "frame-support/std",
  "frame-system/std",
  "sp-io/std",
  "sp-core/std",
  "pallet-transaction-payment/std",
]
try-runtime = ["frame-support/try-runtime"]
