[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Utility for building WASM binaries"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-wasm-builder"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "5.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = "0.12.1"
build-helper = "0.1.1"
cargo_metadata = "0.14.1"
sp-maybe-compressed-blob = {version = "4.1.0-dev", path = "../../primitives/maybe-compressed-blob"}
tempfile = "3.1.0"
toml = "0.5.4"
walkdir = "2.3.2"
wasm-gc-api = "0.1.11"
