[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Cli command runtime testing and dry-running"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "try-runtime-cli"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.8"
parity-scale-codec = {version = "2.3.1"}
serde = "1.0.126"
structopt = "0.3.25"

sc-chain-spec = {version = "4.0.0-dev", path = "../../../../client/chain-spec"}
sc-cli = {version = "0.10.0-dev", path = "../../../../client/cli"}
sc-executor = {version = "0.10.0-dev", path = "../../../../client/executor"}
sc-service = {version = "0.10.0-dev", default-features = false, path = "../../../../client/service"}
sp-core = {version = "4.0.0", path = "../../../../primitives/core"}
sp-externalities = {version = "0.10.0", path = "../../../../primitives/externalities"}
sp-io = {version = "4.0.0-dev", path = "../../../../primitives/io"}
sp-keystore = {version = "0.10.0-dev", path = "../../../../primitives/keystore"}
sp-runtime = {version = "4.0.0-dev", path = "../../../../primitives/runtime"}
sp-state-machine = {version = "0.10.0-dev", path = "../../../../primitives/state-machine"}
sp-version = {version = "4.0.0-dev", path = "../../../../primitives/version"}

jsonrpsee = {version = "0.4.1", default-features = false, features = ["ws-client"]}
remote-externalities = {version = "0.10.0-dev", path = "../../remote-externalities"}

zstd = "0.9.0"
