[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME identity management pallet"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-identity"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "max-encoded-len"]}
enumflags2 = {version = "0.6.2"}
frame-benchmarking = {version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true}
frame-support = {version = "4.0.0-dev", default-features = false, path = "../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../system"}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
sp-io = {version = "4.0.0", default-features = false, path = "../../primitives/io"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../primitives/runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../../primitives/std"}

[dev-dependencies]
pallet-balances = {version = "4.0.0-dev", path = "../balances"}
sp-core = {version = "4.1.0-dev", path = "../../primitives/core"}

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
  "codec/std",
  "scale-info/std",
  "sp-std/std",
  "sp-io/std",
  "sp-runtime/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
]
try-runtime = ["frame-support/try-runtime"]
