[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "This crate provides procedural macros for calculating static hash."
documentation = "https://docs.rs/sp-core-hashing-proc-macro"
edition = "2021"
homepage = "https://substrate.dev"
license = "Apache-2.0"
name = "sp-core-hashing-proc-macro"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.29"
quote = "1.0.6"
sp-core-hashing = {version = "4.0.0", path = "../", default-features = false}
syn = {version = "1.0.81", features = ["full", "parsing"]}
