[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate runtime interface"
documentation = "https://docs.rs/sp-runtime-interface/"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-runtime-interface"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.1.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
impl-trait-for-tuples = "0.2.1"
primitive-types = {version = "0.10.1", default-features = false}
sp-externalities = {version = "0.10.0", optional = true, path = "../externalities"}
sp-runtime-interface-proc-macro = {version = "4.0.0", path = "proc-macro"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}
sp-storage = {version = "4.0.0", default-features = false, path = "../storage"}
sp-tracing = {version = "4.0.0", default-features = false, path = "../tracing"}
sp-wasm-interface = {version = "4.1.0-dev", path = "../wasm-interface", default-features = false}
static_assertions = "1.0.0"

[dev-dependencies]
rustversion = "1.0.6"
sp-core = {version = "4.1.0-dev", path = "../core"}
sp-io = {version = "4.0.0-dev", path = "../io"}
sp-runtime-interface-test-wasm = {version = "2.0.0", path = "test-wasm"}
sp-state-machine = {version = "0.10.0", path = "../state-machine"}
trybuild = "1.0.53"

[features]
default = ["std"]
std = [
  "sp-wasm-interface/std",
  "sp-std/std",
  "sp-tracing/std",
  "codec/std",
  "sp-externalities",
  "primitive-types/std",
]

# ATTENTION
#
# Only use when you know what you are doing.
#
# Disables static assertions in `impls.rs` that checks the word size. To prevent any footgun, the
# check is changed into a runtime check.
disable_target_static_assertions = []
