[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitive core crate hashing implementation."
documentation = "https://docs.rs/sp-core-hashing"
edition = "2021"
homepage = "https://substrate.dev"
license = "Apache-2.0"
name = "sp-core-hashing"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
byteorder = {version = "1.3.2", default-features = false}
sp-std = {version = "4.0.0", default-features = false, path = "../../std"}

blake2-rfc = {version = "0.2.18", default-features = false}
sha2 = {version = "0.9.2", default-features = false}
tiny-keccak = {version = "2.0.1", features = ["keccak"]}
twox-hash = {version = "1.5.0", default-features = false}

[features]
default = ["std"]
std = [
  "blake2-rfc/std",
  "sha2/std",
  "sp-std/std",
  "twox-hash/std",
]
