[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "PoW consensus algorithm for substrate"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-consensus-pow"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.50"
codec = {package = "parity-scale-codec", version = "2.0.0", features = ["derive"]}
derive_more = "0.99.2"
futures = "0.3.16"
futures-timer = "3.0.1"
log = "0.4.8"
parking_lot = "0.11.1"
prometheus-endpoint = {package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.9.0"}
sc-client-api = {version = "4.0.0-dev", path = "../../api"}
sc-consensus = {version = "0.10.0-dev", path = "../../../client/consensus/common"}
sp-api = {version = "4.0.0-dev", path = "../../../primitives/api"}
sp-block-builder = {version = "4.0.0-dev", path = "../../../primitives/block-builder"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
sp-consensus = {version = "0.10.0-dev", path = "../../../primitives/consensus/common"}
sp-consensus-pow = {version = "0.10.0-dev", path = "../../../primitives/consensus/pow"}
sp-core = {version = "4.0.0-dev", path = "../../../primitives/core"}
sp-inherents = {version = "4.0.0-dev", path = "../../../primitives/inherents"}
sp-runtime = {version = "4.0.0-dev", path = "../../../primitives/runtime"}
