[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate externalities abstraction"
documentation = "https://docs.rs/sp-externalities"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-externalities"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
environmental = {version = "1.1.3", default-features = false}
sp-std = {version = "4.0.0", path = "../std", default-features = false}
sp-storage = {version = "4.0.0", path = "../storage", default-features = false}

[features]
default = ["std"]
std = [
  "codec/std",
  "environmental/std",
  "sp-std/std",
  "sp-storage/std",
]
