[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Runtime asynchronous, pure computational tasks"
documentation = "https://docs.rs/sp-tasks"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-tasks"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = {version = "0.4.8", optional = true}
sp-core = {version = "4.0.0", default-features = false, path = "../core"}
sp-externalities = {version = "0.10.0", optional = true, path = "../externalities"}
sp-io = {version = "4.0.0-dev", default-features = false, path = "../io"}
sp-runtime-interface = {version = "4.0.0", default-features = false, path = "../runtime-interface"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}

[dev-dependencies]
codec = {package = "parity-scale-codec", default-features = false, version = "2.0.0"}

[features]
default = ["std"]
std = [
  "log",
  "sp-core/std",
  "sp-externalities",
  "sp-io/std",
  "sp-runtime-interface/std",
  "sp-std/std",
]
