[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Keystore primitives."
documentation = "https://docs.rs/sp-core"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-keystore"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.50"
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
derive_more = "0.99.16"
futures = {version = "0.3.1"}
merlin = {version = "2.0", default-features = false}
parking_lot = {version = "0.11.1", default-features = false}
schnorrkel = {version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false}
serde = {version = "1.0", optional = true}
sp-core = {version = "4.0.0", path = "../core"}
sp-externalities = {version = "0.10.0", path = "../externalities", default-features = false}

[dev-dependencies]
rand = "0.7.2"
rand_chacha = "0.2.2"

[features]
default = ["std"]
std = [
  "serde",
  "schnorrkel/std",
]
