[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "CLI for benchmarking FRAME"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "frame-benchmarking-cli"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
Inflector = "0.11.4"
chrono = "0.4"
codec = {version = "2.0.0", package = "parity-scale-codec"}
frame-benchmarking = {version = "4.0.0-dev", path = "../../../frame/benchmarking"}
frame-support = {version = "4.0.0-dev", path = "../../../frame/support"}
handlebars = "3.5.0"
linked-hash-map = "0.5.4"
log = "0.4.8"
sc-cli = {version = "0.10.0-dev", path = "../../../client/cli"}
sc-client-db = {version = "0.10.0-dev", path = "../../../client/db"}
sc-executor = {version = "0.10.0-dev", path = "../../../client/executor"}
sc-service = {version = "0.10.0-dev", default-features = false, path = "../../../client/service"}
serde = "1.0.126"
sp-core = {version = "4.0.0-dev", path = "../../../primitives/core"}
sp-externalities = {version = "0.10.0-dev", path = "../../../primitives/externalities"}
sp-keystore = {version = "0.10.0-dev", path = "../../../primitives/keystore"}
sp-runtime = {version = "4.0.0-dev", path = "../../../primitives/runtime"}
sp-state-machine = {version = "0.10.0-dev", path = "../../../primitives/state-machine"}
structopt = "0.3.8"

[features]
db = ["sc-client-db/with-kvdb-rocksdb", "sc-client-db/with-parity-db"]
default = ["db"]
