[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "election provider supporting traits"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "frame-election-provider-support"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
frame-support = {version = "4.0.0-dev", default-features = false, path = "../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../system"}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
sp-arithmetic = {version = "4.0.0-dev", default-features = false, path = "../../primitives/arithmetic"}
sp-npos-elections = {version = "4.0.0-dev", default-features = false, path = "../../primitives/npos-elections"}
sp-std = {version = "4.0.0-dev", default-features = false, path = "../../primitives/std"}

[dev-dependencies]
sp-core = {version = "4.0.0-dev", path = "../../primitives/core"}
sp-io = {version = "4.0.0-dev", path = "../../primitives/io"}
sp-npos-elections = {version = "4.0.0-dev", path = "../../primitives/npos-elections"}
sp-runtime = {version = "4.0.0-dev", path = "../../primitives/runtime"}

[features]
default = ["std"]
runtime-benchmarks = []
std = [
  "codec/std",
  "sp-std/std",
  "sp-npos-elections/std",
  "sp-arithmetic/std",
  "frame-support/std",
  "frame-system/std",
]
