[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Authorship primitives"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-authorship"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = {version = "0.1.50", optional = true}
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
sp-inherents = {version = "4.0.0-dev", default-features = false, path = "../inherents"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-std/std",
  "sp-inherents/std",
  "sp-runtime/std",
  "async-trait",
]
