[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-test-client"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.50"
codec = {package = "parity-scale-codec", version = "2.0.0"}
futures = "0.3.16"
hex = "0.4"
sc-client-api = {version = "4.0.0-dev", path = "../../client/api"}
sc-client-db = {version = "0.10.0-dev", features = [
  "test-helpers",
], path = "../../client/db"}
sc-consensus = {version = "0.10.0-dev", path = "../../client/consensus/common"}
sc-executor = {version = "0.10.0-dev", path = "../../client/executor"}
sc-offchain = {version = "4.0.0-dev", path = "../../client/offchain"}
sc-service = {version = "0.10.0-dev", default-features = false, features = [
  "test-helpers",
], path = "../../client/service"}
serde = "1.0.132"
serde_json = "1.0.74"
sp-blockchain = {version = "4.0.0-dev", path = "../../primitives/blockchain"}
sp-consensus = {version = "0.10.0-dev", path = "../../primitives/consensus/common"}
sp-core = {version = "4.1.0-dev", path = "../../primitives/core"}
sp-keyring = {version = "4.1.0-dev", path = "../../primitives/keyring"}
sp-keystore = {version = "0.10.0", path = "../../primitives/keystore"}
sp-runtime = {version = "4.1.0-dev", path = "../../primitives/runtime"}
sp-state-machine = {version = "0.10.0", path = "../../primitives/state-machine"}
