[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME randomness collective flip pallet"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-randomness-collective-flip"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
safe-mix = {version = "1.0", default-features = false}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../../primitives/runtime"}
sp-std = {version = "4.0.0-dev", default-features = false, path = "../../primitives/std"}

frame-support = {version = "4.0.0-dev", default-features = false, path = "../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../system"}

[dev-dependencies]
sp-core = {version = "4.0.0-dev", path = "../../primitives/core"}
sp-io = {version = "4.0.0-dev", path = "../../primitives/io"}

[features]
default = ["std"]
std = [
  "safe-mix/std",
  "codec/std",
  "scale-info/std",
  "sp-runtime/std",
  "sp-std/std",
  "frame-system/std",
  "frame-support/std",
]
try-runtime = ["frame-support/try-runtime"]
