[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Crate with utility functions for `build.rs` scripts."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-build-script-utils"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "3.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
platforms = "1.1"
