[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Support code for the runtime."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "frame-support"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bitflags = "1.3"
codec = {package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "max-encoded-len"]}
frame-metadata = {version = "14.2.0", default-features = false, features = ["v14"]}
frame-support-procedural = {version = "4.0.0-dev", default-features = false, path = "./procedural"}
impl-trait-for-tuples = "0.2.1"
log = {version = "0.4.14", default-features = false}
once_cell = {version = "1", default-features = false, optional = true}
paste = "1.0"
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.132", optional = true, features = ["derive"]}
smallvec = "1.7.0"
sp-arithmetic = {version = "4.0.0", default-features = false, path = "../../primitives/arithmetic"}
sp-core = {version = "4.1.0-dev", default-features = false, path = "../../primitives/core"}
sp-core-hashing-proc-macro = {version = "4.0.0-dev", path = "../../primitives/core/hashing/proc-macro"}
sp-inherents = {version = "4.0.0-dev", default-features = false, path = "../../primitives/inherents"}
sp-io = {version = "4.0.0", default-features = false, path = "../../primitives/io"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../primitives/runtime"}
sp-staking = {version = "4.0.0-dev", default-features = false, path = "../../primitives/staking"}
sp-state-machine = {version = "0.10.0", optional = true, path = "../../primitives/state-machine"}
sp-std = {version = "4.0.0", default-features = false, path = "../../primitives/std"}
sp-tracing = {version = "4.0.0", default-features = false, path = "../../primitives/tracing"}
tt-call = "1.0.8"

[dev-dependencies]
assert_matches = "1.3.0"
frame-system = {version = "4.0.0-dev", path = "../system"}
parity-util-mem = {version = "0.10.2", default-features = false, features = ["primitive-types"]}
pretty_assertions = "1.0.0"

[features]
default = ["std"]
runtime-benchmarks = []
std = [
  "once_cell",
  "serde",
  "sp-io/std",
  "codec/std",
  "scale-info/std",
  "sp-std/std",
  "sp-runtime/std",
  "sp-tracing/std",
  "sp-arithmetic/std",
  "frame-metadata/std",
  "sp-inherents/std",
  "sp-staking/std",
  "sp-state-machine",
  "frame-support-procedural/std",
  "log/std",
]
try-runtime = []
# By default some types have documentation, `no-metadata-docs` allows to reduce the documentation
# in the metadata.
no-metadata-docs = ["frame-support-procedural/no-metadata-docs"]
# By default some types have documentation, `full-metadata-docs` allows to add documentation to
# more types in the metadata.
full-metadata-docs = ["scale-info/docs"]
