[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Macro for defining a runtime version."
documentation = "https://docs.rs/sp-api-proc-macro"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-version-proc-macro"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", features = ["derive"]}
proc-macro2 = "1.0.29"
quote = "1.0.10"
syn = {version = "1.0.80", features = ["full", "fold", "extra-traits", "visit"]}

[dev-dependencies]
sp-version = {version = "4.0.0-dev", path = ".."}
