[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Endpoint to expose Prometheus metrics"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-prometheus-endpoint"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-std = {version = "1.10.0", features = ["unstable"]}
derive_more = "0.99"
futures-util = {version = "0.3.19", default-features = false, features = ["io"]}
hyper = {version = "0.14.16", default-features = false, features = ["http1", "server", "tcp"]}
log = "0.4.8"
prometheus = {version = "0.13.0", default-features = false}
tokio = "1.15"

[dev-dependencies]
hyper = {version = "0.14.16", features = ["client"]}
tokio = {version = "1.15", features = ["rt-multi-thread"]}
