[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Runtime Modules shared primitive types."
documentation = "https://docs.rs/sp-runtime"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-runtime"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.1.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "max-encoded-len"]}
either = {version = "1.5", default-features = false}
hash256-std-hasher = {version = "0.15.2", default-features = false}
impl-trait-for-tuples = "0.2.1"
log = {version = "0.4.14", default-features = false}
parity-util-mem = {version = "0.10.2", default-features = false, features = ["primitive-types"]}
paste = "1.0"
rand = {version = "0.7.2", optional = true}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.132", optional = true, features = ["derive"]}
sp-application-crypto = {version = "4.0.0", default-features = false, path = "../application-crypto"}
sp-arithmetic = {version = "4.0.0", default-features = false, path = "../arithmetic"}
sp-core = {version = "4.1.0-dev", default-features = false, path = "../core"}
sp-io = {version = "4.0.0", default-features = false, path = "../io"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}

[dev-dependencies]
rand = "0.7.2"
serde_json = "1.0.74"
sp-api = {version = "4.0.0-dev", path = "../api"}
sp-state-machine = {version = "0.10.0", path = "../state-machine"}
sp-tracing = {version = "4.0.0", path = "../../primitives/tracing"}
substrate-test-runtime-client = {version = "2.0.0", path = "../../test-utils/runtime/client"}
zstd = "0.9"

[features]
bench = []
default = ["std"]
runtime-benchmarks = []
std = [
  "sp-application-crypto/std",
  "sp-arithmetic/std",
  "codec/std",
  "scale-info/std",
  "log/std",
  "sp-core/std",
  "rand",
  "sp-std/std",
  "sp-io/std",
  "serde",
  "parity-util-mem/std",
  "hash256-std-hasher/std",
  "either/use_std",
]
