[package]
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "node-runtime"
repository = "https://github.com/ultrastable-money/substrate/"
version = "3.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# third-party dependencies
codec = {package = "parity-scale-codec", version = "2.2.0", default-features = false, features = [
  "derive",
  "max-encoded-len",
]}
hex-literal = {version = "0.3.4", optional = true}
log = {version = "0.4.14", default-features = false}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
static_assertions = "1.1.0"

# primitives
node-primitives = {version = "2.0.0", default-features = false, path = "../primitives"}
sp-api = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/api"}
sp-authority-discovery = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/authority-discovery"}
sp-block-builder = {path = "../../../primitives/block-builder", default-features = false, version = "4.0.0-dev"}
sp-consensus-babe = {version = "0.10.0-dev", default-features = false, path = "../../../primitives/consensus/babe"}
sp-core = {version = "4.0.0", default-features = false, path = "../../../primitives/core"}
sp-inherents = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/inherents"}
sp-io = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/io"}
sp-keyring = {version = "4.0.0-dev", optional = true, path = "../../../primitives/keyring"}
sp-npos-elections = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/npos-elections"}
sp-offchain = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/offchain"}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime"}
sp-sandbox = {version = "0.10.0-dev", default-features = false, path = "../../../primitives/sandbox"}
sp-session = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/session"}
sp-staking = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/staking"}
sp-std = {version = "4.0.0", default-features = false, path = "../../../primitives/std"}
sp-transaction-pool = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/transaction-pool"}
sp-version = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/version"}

# frame dependencies
frame-benchmarking = {version = "4.0.0-dev", default-features = false, path = "../../../frame/benchmarking", optional = true}
frame-election-provider-support = {version = "4.0.0-dev", default-features = false, path = "../../../frame/election-provider-support"}
frame-executive = {version = "4.0.0-dev", default-features = false, path = "../../../frame/executive"}
frame-support = {version = "4.0.0-dev", default-features = false, path = "../../../frame/support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../../../frame/system"}
frame-system-benchmarking = {version = "4.0.0-dev", default-features = false, path = "../../../frame/system/benchmarking", optional = true}
frame-system-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, path = "../../../frame/system/rpc/runtime-api/"}
frame-try-runtime = {version = "0.10.0-dev", default-features = false, path = "../../../frame/try-runtime", optional = true}
pallet-asset-tx-payment = {version = "4.0.0-dev", default-features = false, path = "../../../frame/transaction-payment/asset-tx-payment/"}
pallet-assets = {version = "4.0.0-dev", default-features = false, path = "../../../frame/assets"}
pallet-authority-discovery = {version = "4.0.0-dev", default-features = false, path = "../../../frame/authority-discovery"}
pallet-authorship = {version = "4.0.0-dev", default-features = false, path = "../../../frame/authorship"}
pallet-babe = {version = "4.0.0-dev", default-features = false, path = "../../../frame/babe"}
pallet-bags-list = {version = "4.0.0-dev", default-features = false, path = "../../../frame/bags-list"}
pallet-balances = {version = "4.0.0-dev", default-features = false, path = "../../../frame/balances"}
pallet-bounties = {version = "4.0.0-dev", default-features = false, path = "../../../frame/bounties"}
pallet-child-bounties = {version = "4.0.0-dev", default-features = false, path = "../../../frame/child-bounties"}
pallet-collective = {version = "4.0.0-dev", default-features = false, path = "../../../frame/collective"}
pallet-contracts = {version = "4.0.0-dev", default-features = false, path = "../../../frame/contracts"}
pallet-contracts-primitives = {version = "4.0.0-dev", default-features = false, path = "../../../frame/contracts/common/"}
pallet-contracts-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, path = "../../../frame/contracts/rpc/runtime-api/"}
pallet-democracy = {version = "4.0.0-dev", default-features = false, path = "../../../frame/democracy"}
pallet-election-provider-multi-phase = {version = "4.0.0-dev", default-features = false, path = "../../../frame/election-provider-multi-phase"}
pallet-elections-phragmen = {version = "5.0.0-dev", default-features = false, path = "../../../frame/elections-phragmen"}
pallet-gilt = {version = "4.0.0-dev", default-features = false, path = "../../../frame/gilt"}
pallet-grandpa = {version = "4.0.0-dev", default-features = false, path = "../../../frame/grandpa"}
pallet-identity = {version = "4.0.0-dev", default-features = false, path = "../../../frame/identity"}
pallet-im-online = {version = "4.0.0-dev", default-features = false, path = "../../../frame/im-online"}
pallet-indices = {version = "4.0.0-dev", default-features = false, path = "../../../frame/indices"}
pallet-lottery = {version = "4.0.0-dev", default-features = false, path = "../../../frame/lottery"}
pallet-membership = {version = "4.0.0-dev", default-features = false, path = "../../../frame/membership"}
pallet-mmr = {version = "4.0.0-dev", default-features = false, path = "../../../frame/merkle-mountain-range"}
pallet-multisig = {version = "4.0.0-dev", default-features = false, path = "../../../frame/multisig"}
pallet-offences = {version = "4.0.0-dev", default-features = false, path = "../../../frame/offences"}
pallet-offences-benchmarking = {version = "4.0.0-dev", path = "../../../frame/offences/benchmarking", default-features = false, optional = true}
pallet-proxy = {version = "4.0.0-dev", default-features = false, path = "../../../frame/proxy"}
pallet-randomness-collective-flip = {version = "4.0.0-dev", default-features = false, path = "../../../frame/randomness-collective-flip"}
pallet-recovery = {version = "4.0.0-dev", default-features = false, path = "../../../frame/recovery"}
pallet-scheduler = {version = "4.0.0-dev", default-features = false, path = "../../../frame/scheduler"}
pallet-session = {version = "4.0.0-dev", features = [
  "historical",
], path = "../../../frame/session", default-features = false}
pallet-session-benchmarking = {version = "4.0.0-dev", path = "../../../frame/session/benchmarking", default-features = false, optional = true}
pallet-society = {version = "4.0.0-dev", default-features = false, path = "../../../frame/society"}
pallet-staking = {version = "4.0.0-dev", default-features = false, path = "../../../frame/staking"}
pallet-staking-reward-curve = {version = "4.0.0-dev", default-features = false, path = "../../../frame/staking/reward-curve"}
pallet-sudo = {version = "4.0.0-dev", default-features = false, path = "../../../frame/sudo"}
pallet-timestamp = {version = "4.0.0-dev", default-features = false, path = "../../../frame/timestamp"}
pallet-tips = {version = "4.0.0-dev", default-features = false, path = "../../../frame/tips"}
pallet-transaction-payment = {version = "4.0.0-dev", default-features = false, path = "../../../frame/transaction-payment"}
pallet-transaction-payment-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, path = "../../../frame/transaction-payment/rpc/runtime-api/"}
pallet-transaction-storage = {version = "4.0.0-dev", default-features = false, path = "../../../frame/transaction-storage"}
pallet-treasury = {version = "4.0.0-dev", default-features = false, path = "../../../frame/treasury"}
pallet-uniques = {version = "4.0.0-dev", default-features = false, path = "../../../frame/uniques"}
pallet-utility = {version = "4.0.0-dev", default-features = false, path = "../../../frame/utility"}
pallet-vesting = {version = "4.0.0-dev", default-features = false, path = "../../../frame/vesting"}

[build-dependencies]
substrate-wasm-builder = {version = "5.0.0-dev", path = "../../../utils/wasm-builder"}

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-election-provider-multi-phase/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "pallet-assets/runtime-benchmarks",
  "pallet-babe/runtime-benchmarks",
  "pallet-bags-list/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-bounties/runtime-benchmarks",
  "pallet-child-bounties/runtime-benchmarks",
  "pallet-collective/runtime-benchmarks",
  "pallet-contracts/runtime-benchmarks",
  "pallet-democracy/runtime-benchmarks",
  "pallet-elections-phragmen/runtime-benchmarks",
  "pallet-gilt/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",
  "pallet-identity/runtime-benchmarks",
  "pallet-im-online/runtime-benchmarks",
  "pallet-indices/runtime-benchmarks",
  "pallet-lottery/runtime-benchmarks",
  "pallet-membership/runtime-benchmarks",
  "pallet-mmr/runtime-benchmarks",
  "pallet-multisig/runtime-benchmarks",
  "pallet-proxy/runtime-benchmarks",
  "pallet-scheduler/runtime-benchmarks",
  "pallet-society/runtime-benchmarks",
  "pallet-staking/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "pallet-tips/runtime-benchmarks",
  "pallet-transaction-storage/runtime-benchmarks",
  "pallet-treasury/runtime-benchmarks",
  "pallet-utility/runtime-benchmarks",
  "pallet-uniques/runtime-benchmarks",
  "pallet-vesting/runtime-benchmarks",
  "pallet-offences-benchmarking",
  "pallet-session-benchmarking",
  "frame-system-benchmarking",
  "hex-literal",
]
std = [
  "sp-authority-discovery/std",
  "pallet-assets/std",
  "pallet-authority-discovery/std",
  "pallet-authorship/std",
  "sp-consensus-babe/std",
  "pallet-babe/std",
  "pallet-bags-list/std",
  "pallet-balances/std",
  "pallet-bounties/std",
  "sp-block-builder/std",
  "codec/std",
  "scale-info/std",
  "pallet-collective/std",
  "pallet-contracts/std",
  "pallet-contracts-primitives/std",
  "pallet-contracts-rpc-runtime-api/std",
  "pallet-democracy/std",
  "pallet-elections-phragmen/std",
  "frame-executive/std",
  "pallet-gilt/std",
  "pallet-grandpa/std",
  "pallet-im-online/std",
  "pallet-indices/std",
  "sp-inherents/std",
  "pallet-lottery/std",
  "pallet-membership/std",
  "pallet-mmr/std",
  "pallet-multisig/std",
  "pallet-identity/std",
  "pallet-scheduler/std",
  "node-primitives/std",
  "sp-offchain/std",
  "pallet-offences/std",
  "pallet-proxy/std",
  "sp-core/std",
  "pallet-randomness-collective-flip/std",
  "sp-std/std",
  "pallet-session/std",
  "sp-api/std",
  "sp-runtime/std",
  "sp-staking/std",
  "pallet-staking/std",
  "sp-keyring",
  "sp-session/std",
  "pallet-sudo/std",
  "frame-support/std",
  "frame-benchmarking/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "pallet-election-provider-multi-phase/std",
  "pallet-timestamp/std",
  "pallet-tips/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "pallet-transaction-storage/std",
  "pallet-treasury/std",
  "sp-transaction-pool/std",
  "pallet-utility/std",
  "sp-version/std",
  "pallet-society/std",
  "pallet-recovery/std",
  "pallet-uniques/std",
  "pallet-vesting/std",
  "log/std",
  "frame-try-runtime/std",
  "sp-npos-elections/std",
  "sp-io/std",
  "pallet-child-bounties/std",
]
try-runtime = [
  "frame-executive/try-runtime",
  "frame-try-runtime",
  "frame-system/try-runtime",
  "pallet-assets/try-runtime",
  "pallet-authority-discovery/try-runtime",
  "pallet-authorship/try-runtime",
  "pallet-babe/try-runtime",
  "pallet-balances/try-runtime",
  "pallet-bounties/try-runtime",
  "pallet-child-bounties/try-runtime",
  "pallet-collective/try-runtime",
  "pallet-contracts/try-runtime",
  "pallet-democracy/try-runtime",
  "pallet-elections-phragmen/try-runtime",
  "pallet-grandpa/try-runtime",
  "pallet-im-online/try-runtime",
  "pallet-indices/try-runtime",
  "pallet-lottery/try-runtime",
  "pallet-membership/try-runtime",
  "pallet-mmr/try-runtime",
  "pallet-multisig/try-runtime",
  "pallet-identity/try-runtime",
  "pallet-scheduler/try-runtime",
  "pallet-offences/try-runtime",
  "pallet-proxy/try-runtime",
  "pallet-randomness-collective-flip/try-runtime",
  "pallet-session/try-runtime",
  "pallet-staking/try-runtime",
  "pallet-sudo/try-runtime",
  "pallet-election-provider-multi-phase/try-runtime",
  "pallet-timestamp/try-runtime",
  "pallet-tips/try-runtime",
  "pallet-transaction-payment/try-runtime",
  "pallet-treasury/try-runtime",
  "pallet-utility/try-runtime",
  "pallet-society/try-runtime",
  "pallet-recovery/try-runtime",
  "pallet-uniques/try-runtime",
  "pallet-vesting/try-runtime",
  "pallet-gilt/try-runtime",
]
with-tracing = ["frame-executive/with-tracing"]
# Make contract callable functions marked as __unstable__ available. Do not enable
# on live chains as those are subject to change.
contracts-unstable-interface = ["pallet-contracts/unstable-interface"]
# Force `sp-sandbox` to call into the host resident executor. One still need to make sure
# that `sc-executor` gets the `wasmer-sandbox` feature which happens automatically when
# specified on the command line.
# Don't use that on a production chain.
wasmer-sandbox = ["sp-sandbox/wasmer-sandbox"]
