[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME pallet bags list remote test"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-bags-list-remote-tests"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# frame
frame-election-provider-support = {path = "../../election-provider-support", version = "4.0.0-dev"}
frame-support = {path = "../../support", version = "4.0.0-dev"}
frame-system = {path = "../../system", version = "4.0.0-dev"}
pallet-bags-list = {path = "../../bags-list", version = "4.0.0-dev"}
pallet-staking = {path = "../../staking", version = "4.0.0-dev"}

# core
sp-core = {path = "../../../primitives/core", version = "4.1.0-dev"}
sp-runtime = {path = "../../../primitives/runtime", version = "4.1.0-dev"}
sp-std = {path = "../../../primitives/std", version = "4.0.0"}
sp-storage = {path = "../../../primitives/storage", version = "4.0.0"}
sp-tracing = {path = "../../../primitives/tracing", version = "4.0.0"}

# utils
remote-externalities = {path = "../../../utils/frame/remote-externalities", version = "0.10.0-dev"}

# others
clap = "2.34.0"
log = "0.4.14"
structopt = "0.3.25"
tokio = {version = "1", features = ["macros"]}
