[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME offences pallet benchmarking"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-offences-benchmarking"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
frame-benchmarking = {version = "4.0.0-dev", default-features = false, path = "../../benchmarking"}
frame-election-provider-support = {version = "4.0.0-dev", default-features = false, path = "../../election-provider-support"}
frame-support = {version = "4.0.0-dev", default-features = false, path = "../../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../../system"}
pallet-babe = {version = "4.0.0-dev", default-features = false, path = "../../babe"}
pallet-balances = {version = "4.0.0-dev", default-features = false, path = "../../balances"}
pallet-grandpa = {version = "4.0.0-dev", default-features = false, path = "../../grandpa"}
pallet-im-online = {version = "4.0.0-dev", default-features = false, path = "../../im-online"}
pallet-offences = {version = "4.0.0-dev", default-features = false, features = [
  "runtime-benchmarks",
], path = "../../offences"}
pallet-session = {version = "4.0.0-dev", default-features = false, path = "../../session"}
pallet-staking = {version = "4.0.0-dev", default-features = false, features = [
  "runtime-benchmarks",
], path = "../../staking"}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime"}
sp-staking = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/staking"}
sp-std = {version = "4.0.0", default-features = false, path = "../../../primitives/std"}

[dev-dependencies]
pallet-staking-reward-curve = {version = "4.0.0-dev", path = "../../staking/reward-curve"}
pallet-timestamp = {version = "4.0.0-dev", path = "../../timestamp"}
sp-core = {version = "4.0.0", path = "../../../primitives/core"}
sp-io = {version = "4.0.0-dev", path = "../../../primitives/io"}

[features]
default = ["std"]
std = [
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-babe/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-im-online/std",
  "pallet-offences/std",
  "pallet-session/std",
  "pallet-staking/std",
  "sp-runtime/std",
  "sp-staking/std",
  "frame-election-provider-support/std",
  "sp-std/std",
  "codec/std",
  "scale-info/std",
]
