[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Fuzzer for FRAME pallet bags list"
edition = "2021"
homepage = "https://substrate.dev"
license = "Apache-2.0"
name = "pallet-bags-list-fuzzer"
publish = false
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[dependencies]
honggfuzz = "0.5"
rand = {version = "0.8", features = ["std", "small_rng"]}

frame-election-provider-support = {version = "4.0.0-dev", path = "../../election-provider-support", features = ["runtime-benchmarks"]}
pallet-bags-list = {version = "4.0.0-dev", features = ["fuzz"], path = ".."}

[[bin]]
name = "bags-list"
path = "src/main.rs"
