[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate core types and inherents for timestamps."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-timestamp"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = {version = "0.1.50", optional = true}
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
futures-timer = {version = "3.0.2", optional = true}
log = {version = "0.4.8", optional = true}
sp-api = {version = "4.0.0-dev", default-features = false, path = "../api"}
sp-inherents = {version = "4.0.0-dev", default-features = false, path = "../inherents"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}
thiserror = {version = "1.0.30", optional = true}

[features]
default = ["std"]
std = [
  "sp-api/std",
  "sp-std/std",
  "sp-runtime/std",
  "codec/std",
  "sp-inherents/std",
  "thiserror",
  "log",
  "futures-timer",
  "async-trait",
]
