[package]
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
description = "Substrate authority discovery."
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-authority-discovery"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = "0.8"

[dependencies]
async-trait = "0.1"
codec = {package = "parity-scale-codec", default-features = false, version = "2.0.0"}
derive_more = "0.99.2"
futures = "0.3.9"
futures-timer = "3.0.1"
ip_network = "0.4.0"
libp2p = {version = "0.39.1", default-features = false, features = ["kad"]}
log = "0.4.8"
prometheus-endpoint = {package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.9.0"}
prost = "0.8"
rand = "0.7.2"
sc-client-api = {version = "4.0.0-dev", path = "../api"}
sc-network = {version = "0.10.0-dev", path = "../network"}
sp-api = {version = "4.0.0-dev", path = "../../primitives/api"}
sp-authority-discovery = {version = "4.0.0-dev", path = "../../primitives/authority-discovery"}
sp-blockchain = {version = "4.0.0-dev", path = "../../primitives/blockchain"}
sp-core = {version = "4.0.0-dev", path = "../../primitives/core"}
sp-keystore = {version = "0.10.0-dev", path = "../../primitives/keystore"}
sp-runtime = {version = "4.0.0-dev", path = "../../primitives/runtime"}

[dev-dependencies]
quickcheck = "1.0.3"
sp-tracing = {version = "4.0.0-dev", path = "../../primitives/tracing"}
substrate-test-runtime-client = {version = "2.0.0", path = "../../test-utils/runtime/client"}
