[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Transaction pool client facing API."
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-transaction-pool-api"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[dependencies]
futures = {version = "0.3.1"}
log = {version = "0.4.8"}
serde = {version = "1.0.126", features = ["derive"]}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime"}
thiserror = {version = "1.0.30"}

derive_more = {version = "0.99.16"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
