[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate RPC primitives and utilities."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-rpc"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
rustc-hash = "1.1.0"
serde = {version = "1.0.126", features = ["derive"]}
sp-core = {version = "4.0.0-dev", path = "../core"}

[dev-dependencies]
serde_json = "1.0.68"
