[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Collection of allocator implementations."
documentation = "https://docs.rs/sc-allocator"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sc-allocator"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.1.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.11"
sp-core = {version = "4.1.0-dev", path = "../../primitives/core"}
sp-wasm-interface = {version = "4.1.0-dev", path = "../../primitives/wasm-interface"}
thiserror = "1.0.30"
