[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "RPC extensions for the BABE consensus algorithm"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-consensus-babe-rpc"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more = "0.99.2"
futures = "0.3.16"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
sc-consensus-babe = {version = "0.10.0-dev", path = "../"}
sc-consensus-epochs = {version = "0.10.0-dev", path = "../../epochs"}
sc-rpc-api = {version = "0.10.0-dev", path = "../../../rpc-api"}
serde = {version = "1.0.126", features = ["derive"]}
sp-api = {version = "4.0.0-dev", path = "../../../../primitives/api"}
sp-application-crypto = {version = "4.0.0-dev", path = "../../../../primitives/application-crypto"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../../primitives/blockchain"}
sp-consensus = {version = "0.10.0-dev", path = "../../../../primitives/consensus/common"}
sp-consensus-babe = {version = "0.10.0-dev", path = "../../../../primitives/consensus/babe"}
sp-core = {version = "4.0.0-dev", path = "../../../../primitives/core"}
sp-keystore = {version = "0.10.0-dev", path = "../../../../primitives/keystore"}
sp-runtime = {version = "4.0.0-dev", path = "../../../../primitives/runtime"}

[dev-dependencies]
sc-consensus = {version = "0.10.0-dev", path = "../../../consensus/common"}
sc-keystore = {version = "4.0.0-dev", path = "../../../keystore"}
serde_json = "1.0.68"
sp-keyring = {version = "4.0.0-dev", path = "../../../../primitives/keyring"}
substrate-test-runtime-client = {version = "2.0.0", path = "../../../../test-utils/runtime/client"}
tempfile = "3.1.0"
