[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-test-runtime-client"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
futures = "0.3.9"
sc-block-builder = {version = "0.10.0-dev", path = "../../../client/block-builder"}
sc-client-api = {version = "4.0.0-dev", path = "../../../client/api"}
sc-consensus = {version = "0.10.0-dev", path = "../../../client/consensus/common"}
sp-api = {version = "4.0.0-dev", path = "../../../primitives/api"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
sp-consensus = {version = "0.10.0-dev", path = "../../../primitives/consensus/common"}
sp-core = {version = "4.1.0-dev", path = "../../../primitives/core"}
sp-runtime = {version = "4.1.0-dev", path = "../../../primitives/runtime"}
substrate-test-client = {version = "2.0.0", path = "../../client"}
substrate-test-runtime = {version = "2.0.0", path = "../../runtime"}
