[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate block builder"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-block-builder"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", features = [
  "derive",
]}
sc-client-api = {version = "4.0.0-dev", path = "../api"}
sp-api = {version = "4.0.0-dev", path = "../../primitives/api"}
sp-block-builder = {version = "4.0.0-dev", path = "../../primitives/block-builder"}
sp-blockchain = {version = "4.0.0-dev", path = "../../primitives/blockchain"}
sp-core = {version = "4.0.0", path = "../../primitives/core"}
sp-inherents = {version = "4.0.0-dev", path = "../../primitives/inherents"}
sp-runtime = {version = "4.0.0-dev", path = "../../primitives/runtime"}
sp-state-machine = {version = "0.10.0-dev", path = "../../primitives/state-machine"}

[dev-dependencies]
substrate-test-runtime-client = {path = "../../test-utils/runtime/client"}
