[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Minimal fixed point arithmetic primitives and types for runtime."
documentation = "https://docs.rs/sp-arithmetic"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-arithmetic"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
  "derive",
]}
integer-sqrt = "0.1.2"
num-traits = {version = "0.2.8", default-features = false}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.132", optional = true, features = ["derive"]}
sp-debug-derive = {version = "4.0.0", default-features = false, path = "../debug-derive"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}
static_assertions = "1.1.0"

[dev-dependencies]
criterion = "0.3"
primitive-types = "0.10.1"
rand = "0.7.2"

[features]
default = ["std"]
std = [
  "codec/std",
  "scale-info/std",
  "num-traits/std",
  "sp-std/std",
  "serde",
  "sp-debug-derive/std",
]

[[bench]]
harness = false
name = "bench"
