[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Bag threshold generation script for pallet-bag-list and node-runtime."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "node-runtime-generate-bags"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "3.0.0"

[dependencies]
generate-bags = {version = "3.0.0", path = "../"}
node-runtime = {version = "3.0.0-dev", path = "../../../../bin/node/runtime"}

# third-party
structopt = "0.3.21"
