[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Shareable Substrate types."
documentation = "https://docs.rs/sp-core"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-core"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
base58 = {version = "0.2.0", optional = true}
bitflags = "1.3"
byteorder = {version = "1.3.2", default-features = false}
codec = {package = "parity-scale-codec", version = "2.2.0", default-features = false, features = [
  "derive",
  "max-encoded-len",
]}
dyn-clonable = {version = "0.9.0", optional = true}
futures = {version = "0.3.1", optional = true}
hash-db = {version = "0.15.2", default-features = false}
hash256-std-hasher = {version = "0.15.2", default-features = false}
impl-serde = {version = "0.3.0", optional = true}
lazy_static = {version = "1.4.0", default-features = false, optional = true}
log = {version = "0.4.11", default-features = false}
num-traits = {version = "0.2.8", default-features = false}
parity-util-mem = {version = "0.10.0", default-features = false, features = [
  "primitive-types",
]}
parking_lot = {version = "0.11.1", optional = true}
primitive-types = {version = "0.10.1", default-features = false, features = [
  "codec",
  "scale-info",
]}
rand = {version = "0.7.3", optional = true, features = ["small_rng"]}
regex = {version = "1.5.4", optional = true}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
secrecy = {version = "0.8.0", default-features = false}
serde = {version = "1.0.126", optional = true, features = ["derive"]}
sp-debug-derive = {version = "3.0.0", default-features = false, path = "../debug-derive"}
sp-externalities = {version = "0.10.0-dev", optional = true, path = "../externalities"}
sp-std = {version = "4.0.0-dev", default-features = false, path = "../std"}
sp-storage = {version = "4.0.0-dev", default-features = false, path = "../storage"}
substrate-bip39 = {version = "0.4.2", optional = true}
thiserror = {version = "1.0.21", optional = true}
tiny-bip39 = {version = "0.8.2", optional = true}
wasmi = {version = "0.9.0", optional = true}
zeroize = {version = "1.4.2", default-features = false}

# full crypto
blake2-rfc = {version = "0.2.18", default-features = false, optional = true}
ed25519-dalek = {version = "1.0.1", default-features = false, features = [
  "u64_backend",
  "alloc",
], optional = true}
hex = {version = "0.4", default-features = false, optional = true}
libsecp256k1 = {version = "0.6", default-features = false, features = ["hmac", "static-context"], optional = true}
merlin = {version = "2.0", default-features = false, optional = true}
schnorrkel = {version = "0.9.1", features = [
  "preaudit_deprecated",
  "u64_backend",
], default-features = false, optional = true}
sha2 = {version = "0.9.8", default-features = false, optional = true}
sp-runtime-interface = {version = "4.0.0-dev", default-features = false, path = "../runtime-interface"}
ss58-registry = "1.0.0"
tiny-keccak = {version = "2.0.1", features = ["keccak"], optional = true}
twox-hash = {version = "1.6.1", default-features = false, optional = true}

[dev-dependencies]
criterion = "0.3.3"
hex-literal = "0.3.3"
rand = "0.7.2"
serde_json = "1.0"
sp-serializer = {version = "3.0.0", path = "../serializer"}

[[bench]]
harness = false
name = "bench"

[lib]
bench = false

[features]
default = ["std"]
std = [
  "full_crypto",
  "log/std",
  "thiserror",
  "wasmi",
  "lazy_static",
  "parking_lot",
  "primitive-types/std",
  "primitive-types/serde",
  "primitive-types/byteorder",
  "primitive-types/rustc-hex",
  "impl-serde",
  "codec/std",
  "scale-info/std",
  "hash256-std-hasher/std",
  "hash-db/std",
  "sp-std/std",
  "serde",
  "twox-hash/std",
  "blake2-rfc/std",
  "ed25519-dalek/std",
  "hex/std",
  "base58",
  "substrate-bip39",
  "tiny-bip39",
  "byteorder/std",
  "rand",
  "sha2/std",
  "schnorrkel/std",
  "regex",
  "num-traits/std",
  "tiny-keccak",
  "sp-debug-derive/std",
  "sp-externalities",
  "sp-storage/std",
  "sp-runtime-interface/std",
  "zeroize/alloc",
  "secrecy/alloc",
  "futures",
  "futures/thread-pool",
  "libsecp256k1/std",
  "dyn-clonable",
]

# This feature enables all crypto primitives for `no_std` builds like microcontrollers
# or Intel SGX.
# For the regular wasm runtime builds this should not be used.
full_crypto = [
  "ed25519-dalek",
  "blake2-rfc",
  "tiny-keccak",
  "schnorrkel",
  "hex",
  "sha2",
  "twox-hash",
  "libsecp256k1",
  "sp-runtime-interface/disable_target_static_assertions",
  "merlin",
]
