[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Telemetry utils"
documentation = "https://docs.rs/sc-telemetry"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-telemetry"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
chrono = "0.4.19"
futures = "0.3.9"
libp2p = {version = "0.39.1", default-features = false, features = ["dns-async-std", "tcp-async-io", "wasm-ext", "websocket"]}
log = "0.4.8"
parking_lot = "0.11.1"
pin-project = "1.0.8"
rand = "0.7.2"
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0.68"
thiserror = "1.0.21"
wasm-timer = "0.2.5"
