[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Handling of blobs, usually Wasm code, which may be compresed"
documentation = "https://docs.rs/sp-maybe-compressed-blob"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-maybe-compressed-blob"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.1.0-dev"

[dependencies]
zstd = {version = "0.9.0", default-features = false}
