[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate customizable serde serializer."
documentation = "https://docs.rs/sp-serializer"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-serializer"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = "1.0.132"
serde_json = "1.0.74"
