[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "This crate provides procedural macros for usage within the context of the Substrate runtime interface."
documentation = "https://docs.rs/sp-runtime-interface-proc-macro"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-runtime-interface-proc-macro"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.36"
quote = "1.0.10"
syn = {version = "1.0.82", features = ["full", "visit", "fold", "extra-traits"]}
