[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate test utilities macros"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-test-utils-derive"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[dependencies]
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.36"
quote = "1.0.10"
syn = {version = "1.0.82", features = ["full"]}

[lib]
proc-macro = true
