[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Provides types and traits for creating and checking inherents."
documentation = "https://docs.rs/sp-inherents"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-inherents"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = {version = "0.1.50", optional = true}
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
impl-trait-for-tuples = "0.2.0"
sp-core = {version = "4.0.0", default-features = false, path = "../core"}
sp-runtime = {version = "4.0.0-dev", path = "../runtime", optional = true}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}
thiserror = {version = "1.0.30", optional = true}

[dev-dependencies]
futures = "0.3.9"

[features]
default = ["std"]
std = [
  "sp-std/std",
  "codec/std",
  "sp-core/std",
  "thiserror",
  "sp-runtime",
  "async-trait",
]
