[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate blockchain traits and primitives."
documentation = "https://docs.rs/sp-blockchain"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-blockchain"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
futures = "0.3.9"
log = "0.4.11"
lru = "0.7.0"
parking_lot = "0.11.1"
sp-api = {version = "4.0.0-dev", path = "../api"}
sp-consensus = {version = "0.10.0-dev", path = "../consensus/common"}
sp-database = {version = "4.0.0-dev", path = "../database"}
sp-runtime = {version = "4.0.0-dev", path = "../runtime"}
sp-state-machine = {version = "0.10.0-dev", path = "../state-machine"}
thiserror = "1.0.30"
