[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for VRF based consensus"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-consensus-vrf"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {version = "2.0.0", package = "parity-scale-codec", default-features = false}
schnorrkel = {version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false}
sp-core = {version = "4.1.0-dev", path = "../../core", default-features = false}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../runtime"}
sp-std = {version = "4.0.0", path = "../../std", default-features = false}

[features]
default = ["std"]
std = [
  "codec/std",
  "schnorrkel/std",
  "sp-std/std",
  "sp-core/std",
  "sp-runtime/std",
]
