[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Collection of common consensus specific imlementations for Substrate (client)"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-consensus"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.42"
futures = {version = "0.3.1", features = ["thread-pool"]}
futures-timer = "3.0.1"
libp2p = {version = "0.40.0", default-features = false}
log = "0.4.8"
parking_lot = "0.11.2"
prometheus-endpoint = {package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.10.0-dev"}
sc-client-api = {version = "4.0.0-dev", path = "../../api"}
sc-utils = {version = "4.0.0-dev", path = "../../utils"}
serde = {version = "1.0", features = ["derive"]}
sp-api = {version = "4.0.0-dev", path = "../../../primitives/api"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
sp-consensus = {path = "../../../primitives/consensus/common", version = "0.10.0-dev"}
sp-core = {path = "../../../primitives/core", version = "4.1.0-dev"}
sp-runtime = {version = "4.1.0-dev", path = "../../../primitives/runtime"}
sp-state-machine = {version = "0.10.0", path = "../../../primitives/state-machine"}
thiserror = "1.0.30"

[dev-dependencies]
sp-test-primitives = {version = "2.0.0", path = "../../../primitives/test-primitives"}
