[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Runtime API definition required by Contracts RPC extensions."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-contracts-rpc-runtime-api"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"]}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}

# Substrate Dependencies
pallet-contracts-primitives = {version = "4.0.0-dev", default-features = false, path = "../../common"}
sp-api = {version = "4.0.0-dev", default-features = false, path = "../../../../primitives/api"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../../../../primitives/runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../../../../primitives/std"}

[features]
default = ["std"]
std = [
  "sp-api/std",
  "codec/std",
  "scale-info/std",
  "sp-std/std",
  "sp-runtime/std",
  "pallet-contracts-primitives/std",
]
