[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate database trait."
documentation = "https://docs.rs/sp-database"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-database"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[dependencies]
kvdb = "0.10.0"
parking_lot = "0.11.2"
