[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "NPoS Solution Type"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-npos-elections-solution-type"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.29"
quote = "1.0"
syn = {version = "1.0.81", features = ["full", "visit"]}

[dev-dependencies]
parity-scale-codec = "2.3.1"
scale-info = "1.0"
sp-arithmetic = {path = "../../arithmetic", version = "4.0.0-dev"}
# used by generate_solution_type:
sp-npos-elections = {path = "..", version = "4.0.0-dev"}
trybuild = "1.0.52"
