[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Fuzzer for phragmén implementation."
documentation = "https://docs.rs/sp-npos-elections-fuzzer"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-npos-elections-fuzzer"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0-alpha.5"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
honggfuzz = "0.5"
rand = {version = "0.7.3", features = ["std", "small_rng"]}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
sp-npos-elections = {version = "4.0.0-dev", path = ".."}
sp-runtime = {version = "4.1.0-dev", path = "../../runtime"}
structopt = "0.3.25"

[[bin]]
name = "reduce"
path = "src/reduce.rs"

[[bin]]
name = "phragmen_balancing"
path = "src/phragmen_balancing.rs"

[[bin]]
name = "phragmms_balancing"
path = "src/phragmms_balancing.rs"

[[bin]]
name = "compact"
path = "src/compact.rs"

[[bin]]
name = "phragmen_pjr"
path = "src/phragmen_pjr.rs"
