[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Proc macro helpers for procedural macros"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "frame-support-procedural-tools"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-support-procedural-tools-derive = {version = "3.0.0", path = "./derive"}
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.36"
quote = "1.0.10"
syn = {version = "1.0.82", features = ["full", "visit", "extra-traits"]}
