[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-test-primitives"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
parity-util-mem = {version = "0.10.0", default-features = false, features = ["primitive-types"]}
serde = {version = "1.0.126", optional = true, features = ["derive"]}
sp-application-crypto = {version = "4.0.0-dev", default-features = false, path = "../application-crypto"}
sp-core = {version = "4.0.0-dev", default-features = false, path = "../core"}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../runtime"}

[features]
default = [
  "std",
]
std = [
  "sp-application-crypto/std",
  "serde",
]
