[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate runtime api primitives"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-api"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
hash-db = {version = "0.15.2", optional = true}
sp-api-proc-macro = {version = "4.0.0-dev", path = "proc-macro"}
sp-core = {version = "4.0.0", default-features = false, path = "../core"}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../runtime"}
sp-state-machine = {version = "0.10.0-dev", optional = true, path = "../state-machine"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}
sp-version = {version = "4.0.0-dev", default-features = false, path = "../version"}
thiserror = {version = "1.0.30", optional = true}

log = {version = "0.4.14", default-features = false}

[dev-dependencies]
sp-test-primitives = {version = "2.0.0", path = "../test-primitives"}

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-core/std",
  "sp-std/std",
  "sp-runtime/std",
  "sp-state-machine",
  "sp-version/std",
  "hash-db",
  "thiserror",
  "log/std",
]
# Special feature to disable logging completly.
#
# By default `sp-api` initializes the `RuntimeLogger` for each runtime api function. However,
# logging functionality increases the code size. It is recommended to enable this feature when
# building a runtime for registering it on chain.
#
# This sets the max logging level to `off` for `log`.
disable-logging = ["log/max_level_off"]
