[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "node-executor"
repository = "https://github.com/ultrastable-money/substrate/"
version = "3.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
frame-benchmarking = {version = "4.0.0-dev", path = "../../../frame/benchmarking"}
node-primitives = {version = "2.0.0", path = "../primitives"}
node-runtime = {version = "3.0.0-dev", path = "../runtime"}
sc-executor = {version = "0.10.0-dev", path = "../../../client/executor"}
scale-info = {version = "1.0", features = ["derive"]}
sp-core = {version = "4.0.0-dev", path = "../../../primitives/core"}
sp-keystore = {version = "0.10.0-dev", path = "../../../primitives/keystore"}
sp-state-machine = {version = "0.10.0-dev", path = "../../../primitives/state-machine"}
sp-trie = {version = "4.0.0-dev", path = "../../../primitives/trie"}

[dev-dependencies]
criterion = "0.3.0"
frame-support = {version = "4.0.0-dev", path = "../../../frame/support"}
frame-system = {version = "4.0.0-dev", path = "../../../frame/system"}
futures = "0.3.9"
node-testing = {version = "3.0.0-dev", path = "../testing"}
pallet-balances = {version = "4.0.0-dev", path = "../../../frame/balances"}
pallet-contracts = {version = "4.0.0-dev", path = "../../../frame/contracts"}
pallet-im-online = {version = "4.0.0-dev", path = "../../../frame/im-online"}
pallet-timestamp = {version = "4.0.0-dev", path = "../../../frame/timestamp"}
pallet-treasury = {version = "4.0.0-dev", path = "../../../frame/treasury"}
sp-application-crypto = {version = "4.0.0-dev", path = "../../../primitives/application-crypto"}
sp-consensus-babe = {version = "0.10.0-dev", path = "../../../primitives/consensus/babe"}
sp-externalities = {version = "0.10.0-dev", path = "../../../primitives/externalities"}
sp-runtime = {version = "4.0.0-dev", path = "../../../primitives/runtime"}
wat = "1.0"

[features]
stress-test = []
wasmi-errno = ["sc-executor/wasmi-errno"]
wasmtime = ["sc-executor/wasmtime"]

[[bench]]
harness = false
name = "bench"
