[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME pallet for democracy"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "frame-try-runtime"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = {version = "4.0.0-dev", path = "../../primitives/api", default-features = false}
sp-runtime = {version = "4.0.0-dev", path = "../../primitives/runtime", default-features = false}
sp-std = {version = "4.0.0", path = "../../primitives/std", default-features = false}

frame-support = {version = "4.0.0-dev", path = "../support", default-features = false}

[features]
default = ["std"]
std = [
  "sp-api/std",
  "sp-std/std",
  "sp-runtime/std",
  "frame-support/std",
]
