[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Reward Curve for FRAME staking pallet"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-staking-reward-curve"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.36"
quote = "1.0.10"
syn = {version = "1.0.82", features = ["full", "visit"]}

[dev-dependencies]
sp-runtime = {version = "4.1.0-dev", path = "../../../primitives/runtime"}
