[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Version module for the Substrate runtime; Provides a function that returns the runtime version."
documentation = "https://docs.rs/sp-version"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "sp-version"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
impl-serde = {version = "0.3.1", optional = true}
parity-wasm = {version = "0.42.2", optional = true}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.132", optional = true, features = ["derive"]}
sp-core-hashing-proc-macro = {version = "4.0.0-dev", path = "../core/hashing/proc-macro"}
sp-runtime = {version = "4.1.0-dev", default-features = false, path = "../runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../std"}
sp-version-proc-macro = {version = "4.0.0-dev", default-features = false, path = "proc-macro"}
thiserror = {version = "1.0.30", optional = true}

[features]
default = ["std"]
std = [
  "impl-serde",
  "serde",
  "codec/std",
  "scale-info/std",
  "sp-std/std",
  "sp-runtime/std",
  "parity-wasm",
  "thiserror",
]
