[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Reward function for FRAME staking pallet"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-staking-reward-fn"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]

[dependencies]
log = {version = "0.4.14", default-features = false}
sp-arithmetic = {version = "4.0.0", default-features = false, path = "../../../primitives/arithmetic"}

[features]
default = ["std"]
std = [
  "sp-arithmetic/std",
  "log/std",
]
