[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Proc macro of Support code for the runtime."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "frame-support-procedural"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
frame-support-procedural-tools = {version = "4.0.0-dev", path = "./tools"}
proc-macro2 = "1.0.29"
quote = "1.0.10"
syn = {version = "1.0.81", features = ["full"]}

[features]
default = ["std"]
std = []
