[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "RPC extensions for the GRANDPA finality gadget"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-finality-grandpa-rpc"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[dependencies]
derive_more = "0.99.2"
finality-grandpa = {version = "0.14.4", features = ["derive-codec"]}
futures = "0.3.16"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-pubsub = "18.0.0"
log = "0.4.8"
parity-scale-codec = {version = "2.0.0", features = ["derive"]}
sc-client-api = {version = "4.0.0-dev", path = "../../api"}
sc-finality-grandpa = {version = "0.10.0-dev", path = "../"}
sc-rpc = {version = "4.0.0-dev", path = "../../rpc"}
serde = {version = "1.0.105", features = ["derive"]}
serde_json = "1.0.50"
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
sp-core = {version = "4.1.0-dev", path = "../../../primitives/core"}
sp-runtime = {version = "4.1.0-dev", path = "../../../primitives/runtime"}

[dev-dependencies]
sc-block-builder = {version = "0.10.0-dev", path = "../../block-builder"}
sc-rpc = {version = "4.0.0-dev", path = "../../rpc", features = [
  "test-helpers",
]}
sp-core = {version = "4.1.0-dev", path = "../../../primitives/core"}
sp-finality-grandpa = {version = "4.0.0-dev", path = "../../../primitives/finality-grandpa"}
sp-keyring = {version = "4.1.0-dev", path = "../../../primitives/keyring"}
substrate-test-runtime-client = {version = "2.0.0", path = "../../../test-utils/runtime/client"}
