[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "substrate-test-runtime-transaction-pool"
publish = false
repository = "https://github.com/ultrastable-money/substrate/"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0"}
derive_more = "0.99.16"
futures = "0.3.16"
parking_lot = "0.11.1"
sc-transaction-pool = {version = "4.0.0-dev", path = "../../../client/transaction-pool", features = ["test-helpers"]}
sc-transaction-pool-api = {version = "4.0.0-dev", path = "../../../client/transaction-pool/api"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
sp-runtime = {version = "4.0.0-dev", path = "../../../primitives/runtime"}
substrate-test-runtime-client = {version = "2.0.0", path = "../client"}
