[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME sessions pallet"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-session"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
impl-trait-for-tuples = "0.2.1"
log = {version = "0.4.0", default-features = false}

codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}

sp-core = {version = "4.0.0-dev", default-features = false, path = "../../primitives/core"}
sp-io = {version = "4.0.0-dev", default-features = false, path = "../../primitives/io"}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../../primitives/runtime"}
sp-session = {version = "4.0.0-dev", default-features = false, path = "../../primitives/session"}
sp-staking = {version = "4.0.0-dev", default-features = false, path = "../../primitives/staking"}
sp-std = {version = "4.0.0-dev", default-features = false, path = "../../primitives/std"}
sp-trie = {version = "4.0.0-dev", default-features = false, path = "../../primitives/trie", optional = true}

frame-support = {version = "4.0.0-dev", default-features = false, path = "../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../system"}
pallet-timestamp = {version = "4.0.0-dev", default-features = false, path = "../timestamp"}

[features]
default = ["std", "historical"]
historical = ["sp-trie"]
std = [
  "log/std",
  "codec/std",
  "scale-info/std",
  "sp-std/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-staking/std",
  "sp-trie/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-timestamp/std",
]
try-runtime = ["frame-support/try-runtime"]
