[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Bag threshold generation script for pallet-bag-list"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "generate-bags"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[dependencies]
# FRAME
frame-election-provider-support = {version = "4.0.0-dev", path = "../../../frame/election-provider-support", features = ["runtime-benchmarks"]}
frame-support = {version = "4.0.0-dev", path = "../../../frame/support"}
frame-system = {version = "4.0.0-dev", path = "../../../frame/system"}
pallet-staking = {version = "4.0.0-dev", path = "../../../frame/staking"}

# primitives
sp-io = {version = "4.0.0", path = "../../../primitives/io"}

# third party
chrono = {version = "0.4.19"}
git2 = {version = "0.13.25", default-features = false}
num-format = {version = "0.4.0"}
structopt = "0.3.25"
