[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic epochs-based utilities for consensus"
edition = "2021"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-consensus-epochs"
readme = "README.md"
repository = "https://github.com/ultrastable-money/substrate/"
version = "0.10.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", features = ["derive"]}
fork-tree = {version = "3.0.0", path = "../../../utils/fork-tree"}
sc-client-api = {path = "../../api", version = "4.0.0-dev"}
sc-consensus = {path = "../common", version = "0.10.0-dev"}
sp-blockchain = {version = "4.0.0-dev", path = "../../../primitives/blockchain"}
sp-runtime = {path = "../../../primitives/runtime", version = "4.0.0-dev"}
