[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "FRAME Merkle Mountain Range primitives."
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-mmr-primitives"
repository = "https://github.com/ultrastable-money/substrate/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
log = {version = "0.4.14", default-features = false}
serde = {version = "1.0.126", optional = true, features = ["derive"]}

sp-api = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/api"}
sp-core = {version = "4.0.0", default-features = false, path = "../../../primitives/core"}
sp-runtime = {version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime"}
sp-std = {version = "4.0.0", default-features = false, path = "../../../primitives/std"}

frame-support = {version = "4.0.0-dev", default-features = false, path = "../../support"}
frame-system = {version = "4.0.0-dev", default-features = false, path = "../../system"}

[dev-dependencies]
hex-literal = "0.3"

[features]
default = ["std"]
std = [
  "codec/std",
  "log/std",
  "serde",
  "sp-api/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std",
  "frame-support/std",
  "frame-system/std",
]
